### ISSUE TITLE
help on understanding the code

### ISSUE THREAD

**Issue by bsr203** [Anaminus/rbxmk#14]
Hi,

I stumbled upon your project while learning lua as a way to support plugin like extension to my go program. Mainly to define workflow or a way to describe custom behavior. your code is extremely well written and documented. I never used `Roblox` or any background in gaming, so couldn't really understand what are the inputs and what kind of modifications can be done through scripting . It would be great if you can provide a sample file and a quick walkthrough how you apply transform through lua file.  Greatly appreciate your time on this.

Thanks,
bsr.

**Comment by Anaminus** [comment]
Issue has been invalidated by v0.3.0 refactor.
