### ISSUE TITLE
rbxmk Usage

### ISSUE THREAD

**Issue by ZappyDCG** [Anaminus/rbxmk#48]
When I try to open the file, nothing happens. When I click it to much a temp output show's up, mind explaining how to install it?

**Comment by fredgig** [comment]
Did you follow the [installation guide](https://github.com/Anaminus/rbxmk#installation)?

If you come across any issue/bug, then you should create a new issue.

**Comment by Anaminus** [comment]
rbxmk is a command-line tool, and so requires a [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) to use. Some examples for Windows are [PowerShell](https://en.wikipedia.org/wiki/PowerShell) or [cmd.exe](https://en.wikipedia.org/wiki/Cmd.exe).

If you have any questions about CLIs, there's a good chance that searching for the question will give you an answer. I've found that this video provides a good general introduction to CLIs:

https://www.youtube.com/watch?v=mUXVBMhr7Xg
