### ISSUE TITLE
Allow access to all file system paths

### ISSUE THREAD

**Issue by AsyxRoblox** [Anaminus/rbxmk#59]
The docs says that for safety reasons the access is limited.

Would it be possible to leave this to be the default behavior but then add some DANGEROUS_ALLOW_ENTIRE_FILE_SYSTEM flag on startup for the "run" command?

I'd like to store certain security information elsewhere on the disk and not in the game repository (even though I could git-ignore it).

**Comment by Anaminus** [comment]
You can add any number of `--include-root PATH` flags to allow specific directories. There's also the `--allow-insecure-paths` flag to allow access to everything.

For more help in general, I recommend browsing through the `rbxmk help` command in a CLI. It offers some information that isn't currently in the documentation.

**Comment by AsyxRoblox** [comment]
Ah I see, thank you!
