### ISSUE TITLE
Is it possible to run an external cmd/bat file?

### ISSUE THREAD

**Issue by AsyxRoblox** [Anaminus/rbxmk#60]
Is it possible to run a custom exe/bat file from the lua run command script?

**Comment by Anaminus** [comment]
It is not possible to run executable files. While it could be added, I'm feeling that it's outside the scope of rbxmk. The recommended workflow is to run rbxmk, among other commands, from a shell script, rather than the other way around.

**Comment by AsyxRoblox** [comment]
Thanks for the reply, I understand.
